baseURL = 'http://www.torb.no/'
languageCode = 'en-us'
title = 'Torb Lunde Miranda'
theme = 'TLM2021'
publishdir = 'docs'
[markup.goldmark.renderer]
    unsafe = true
[markup.highlight]
    noClasses = false